Repository cse403trackforever/webapp, pull requests merged in 2018-04, with the labels that each got.

#10 [Add] Import Plugin For GitHub
  src/app/import/api/fetch-github.service.ts
  src/app/import/import-github.service.ts
  src/app/import/models/github/github-comment.ts
  src/app/import/models/github/github-issue.ts
  src/app/import/models/github/github-label.ts
  src/app/import/models/github/github-owner.ts
  src/app/import/models/github/github-project.ts
  src/app/import/models/trackforever/trackforever-comment.ts
  src/app/import/models/trackforever/trackforever-issue.ts
  src/app/import/models/trackforever/trackforever-project.ts
Labels: enhancement

#33 [Add] import for google code to project import
  src/app/import/api/fetch-googlecode.service.ts
  src/app/import/import-googlecode/import-googlecode.component.css
  src/app/import/import-googlecode/import-googlecode.component.html
  src/app/import/import-googlecode/import-googlecode.component.spec.ts
  src/app/import/import-googlecode/import-googlecode.component.ts
  src/app/import/import-page/import-page.component.html
  src/app/import/import-page/import-page.component.ts
  src/app/import/import.module.ts
Labels: bug

#39 Add database and refactor import
  e2e/app.e2e-spec.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/database/data.service.spec.ts
  src/app/database/data.service.ts
  src/app/database/database.module.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.spec.ts
  src/app/import/convert.service.spec.ts
  src/app/import/convert.service.ts
  src/app/import/import-github.service.spec.ts
  src/app/import/import-github.service.ts
  src/app/import/import-github/import-github.component.spec.ts
  src/app/import/import-github/import-github.component.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-googlecode/import-googlecode.component.spec.ts
  src/app/import/import-googlecode/import-googlecode.component.ts
  src/app/import/import-trackforever.service.ts
  src/app/import/import-trackforever/import-trackforever.component.spec.ts
  src/app/import/import-trackforever/import-trackforever.component.ts
  src/app/import/import.component.ts
  src/app/import/import.module.ts
  src/app/import/import.service.spec.ts
  src/app/import/import.service.ts
  src/app/issue.service.spec.ts
  src/app/issue.service.ts
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.spec.ts
  src/app/project-page/project-page.component.ts
  src/app/shared/pipes/dbkey.pipe.spec.ts
  src/app/shared/pipes/dbkey.pipe.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#43 [Add] error messages for failed import
  package-lock.json
  package.json
  src/app/import/import-page/import-page.component.html
  src/app/import/import-page/import-page.component.ts
  src/app/import/import-trackforever.service.ts
  src/app/import/import.component.ts
  src/app/import/import.service.ts
Labels: user interface

#45 Fix deploy and prod configuration
  .travis.yml
  src/environments/environment.prod.ts
Labels: bug
