Repository cse403trackforever/webapp, pull requests merged in 2018-05, with the labels that each got.

#55 [Fix] bootstrap issues
  src/app/app.component.html
  src/app/app.component.ts
  src/app/home-page/home-page.component.html
  src/app/project-page/project-page.component.html
Labels: bug, user interface

#58 [Add] more rules to tslint
  e2e/app.e2e-spec.ts
  src/app/import/api/fetch-trackforever.service.spec.ts
  src/app/import/api/fetch-trackforever.service.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-trackforever.service.spec.ts
  src/app/import/import-trackforever.service.ts
  src/app/import/import-trackforever/import-trackforever.component.spec.ts
  src/app/import/import-trackforever/import-trackforever.component.ts
  src/app/issue-page/issue-page.component.ts
  tslint.json
Labels: enhancement

#59 [Add] hash codes
  package-lock.json
  package.json
  src/app/import/import-github.service.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-redmine.service.ts
  src/app/import/models/trackforever/mock/mock-trackforever-project.ts
  src/app/import/models/trackforever/trackforever-comment.ts
  src/app/import/models/trackforever/trackforever-issue.ts
  src/app/import/models/trackforever/trackforever-project.ts
  src/app/sync/sync.module.ts
  src/app/sync/sync.service.ts
Labels: enhancement

#56 [Add] font awesome
  .angular-cli.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.spec.ts
  src/app/home-page/home-page.component.ts
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.spec.ts
  src/app/project-page/project-page.component.ts
  src/app/signin-page/signin-page.component.html
  src/app/signin-page/signin-page.component.spec.ts
  src/app/signin-page/signin-page.component.ts
  tsconfig.json
Labels: enhancement, user interface

#79 Switch issue array to map
  package-lock.json
  package.json
  src/app/export/export.service.spec.ts
  src/app/export/export.service.ts
  src/app/import/import-github.service.spec.ts
  src/app/import/import-github.service.ts
  src/app/import/import-googlecode.service.spec.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-redmine.service.spec.ts
  src/app/import/import-redmine.service.ts
  src/app/import/import-trackforever.service.spec.ts
  src/app/import/import-trackforever.service.ts
  src/app/import/models/redmine/mock/mock-redmine-trackforever-project.ts
  src/app/import/models/trackforever/mock/mock-trackforever-project.ts
  src/app/import/models/trackforever/trackforever-project.ts
  src/app/issue/offline-issue.service.spec.ts
  src/app/issue/offline-issue.service.ts
  src/app/issue/online-issue.service.spec.ts
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.ts
  src/app/sync/sync.service.ts
Labels: enhancement

#85 Add GitHub pagination
  src/app/import/api/fetch-github.service.spec.ts
  src/app/import/api/fetch-github.service.ts
  src/app/import/import-github.service.spec.ts
  src/app/import/import-github.service.ts
  src/app/import/import.service.ts
Labels: bug

#87 Fix missing GoogleCode pages
  src/app/import/api/fetch-googlecode.service.spec.ts
  src/app/import/import-googlecode.service.spec.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/models/googlecode/mock/issues-1.json
  src/app/import/models/googlecode/mock/issues-2.json
  src/app/import/models/googlecode/mock/issues-3.json
  src/app/import/models/googlecode/mock/issues-page-1.json
  src/app/import/models/googlecode/mock/issues-page-2.json
  src/app/import/models/googlecode/mock/issues-page-3.json
  src/app/import/models/googlecode/mock/issues.json
  src/app/import/models/googlecode/mock/project.json
Labels: bug

#89 Add issue and project pagination
  src/app/my-projects-page/my-projects-page.component.html
  src/app/my-projects-page/my-projects-page.component.spec.ts
  src/app/my-projects-page/my-projects-page.component.ts
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.spec.ts
  src/app/project-page/project-page.component.ts
Labels: user interface

#90 Format dates
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/issue-page/issue-page.component.html
  src/app/issue-page/issue-page.component.spec.ts
Labels: user interface

#92 Shorten base href
  .travis.yml
  src/environments/environment.prod.ts
Labels: bug

#86 Add delta/diff code
  package-lock.json
  src/app/app.module.ts
  src/app/database/data.service.spec.ts
  src/app/database/data.service.ts
  src/app/database/database.module.ts
  src/app/home-page/home-page.component.spec.ts
  src/app/import/import-github.service.spec.ts
  src/app/import/import-github.service.ts
  src/app/import/import-googlecode.service.spec.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-redmine.service.ts
  src/app/import/models/redmine/mock/mock-redmine-trackforever-project.ts
  src/app/issue/offline-issue.service.spec.ts
  src/app/issue/offline-issue.service.ts
  src/app/issue/online-issue.service.spec.ts
  src/app/issue/online-issue.service.ts
  src/app/my-projects-page/my-projects-page.component.html
  src/app/my-projects-page/my-projects-page.component.spec.ts
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.spec.ts
  src/app/shared/pipes/dbkey.pipe.spec.ts
  src/app/shared/pipes/dbkey.pipe.ts
  src/app/sync/hash-response.ts
  src/app/sync/sync.service.spec.ts
  src/app/sync/sync.service.ts
Labels: enhancement

#93 [Fix] bootstrap inputs for Firefox
  src/app/import/import-page/import-page.component.html
  src/app/import/import-trackforever/import-trackforever.component.html
  src/app/import/import-trackforever/import-trackforever.component.ts
Labels: user interface

#96 [Fix] single page case for github issues
  src/app/import/import-github.service.spec.ts
  src/app/import/import-github.service.ts
Labels: bug

#97 Firebase hosting
  .firebaserc
  .travis.yml
  firebase.json
Labels: enhancement

#94 Add basic search and label filtering
  src/app/app.module.ts
  src/app/project-page/project-page.component.css
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.spec.ts
  src/app/project-page/project-page.component.ts
Labels: enhancement, user interface

#100 Fix premature getProjects completion in offline issue service
  src/app/issue/offline-issue.service.spec.ts
  src/app/issue/offline-issue.service.ts
Labels: bug

#101 [Fix] broken mobile layout on mobile and lack of branding
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/home-page/home-page.component.css
  src/app/home-page/home-page.component.html
  src/app/signin-page/signin-page.component.css
  src/app/signin-page/signin-page.component.html
  src/styles.css
Labels: enhancement, user interface

#108 Angular 6
  .angular-cli.json
  .travis.yml
  angular.json
  karma.conf.js
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/home-page/home-page.component.spec.ts
  src/app/issue-page/issue-page.component.spec.ts
  src/app/sync/sync.service.spec.ts
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/index.html
  src/manifest.json
  src/tsconfig.spec.json
  tslint.json
Labels: enhancement

#128 [Remove] all wrapper TS classes
  src/app/import/api/fetch-googlecode.service.ts
  src/app/import/api/fetch-redmine.service.ts
  src/app/import/import-github.service.ts
  src/app/import/import-page/import-page.component.ts
  src/app/import/import-redmine.service.spec.ts
  src/app/import/import-redmine.service.ts
  src/app/import/import-redmine/import-redmine.component.ts
  src/app/import/import.component.ts
  src/app/import/models/github/github-comment.ts
  src/app/import/models/github/github-issue.ts
  src/app/import/models/github/github-label.ts
  src/app/import/models/github/github-owner.ts
  src/app/import/models/github/github-project.ts
  src/app/import/models/googlecode/googlecode-attachment.ts
  src/app/import/models/googlecode/googlecode-comment.ts
  src/app/import/models/googlecode/googlecode-issue.ts
  src/app/import/models/googlecode/googlecode-issuepage.ts
  src/app/import/models/googlecode/googlecode-issuesummary.ts
  src/app/import/models/googlecode/googlecode-project.ts
  src/app/import/models/redmine/redmine-issue-substructure.ts
  src/app/import/models/redmine/redmine-issue.ts
  src/app/import/models/redmine/redmine-issueArray.ts
  src/app/import/models/redmine/redmine-project.ts
  src/app/import/models/trackforever/trackforever-issue.ts
  src/app/project-page/project-page.component.html
Labels: bug

#129 [Update] bad style while loops to be for loops
  src/app/import/import-github.service.ts
  src/app/import/import-googlecode.service.ts
  src/app/import/import-redmine.service.ts
Labels: bug

#137 Switch -1 to null and fix date issue
  src/app/import/import-github/import-github.service.spec.ts
  src/app/import/import-github/import-github.service.ts
  src/app/import/import-googlecode/import-googlecode.service.spec.ts
  src/app/import/import-googlecode/import-googlecode.service.ts
  src/app/import/import-redmine/import-redmine.service.ts
  src/app/import/import-redmine/models/mock/mock-redmine-trackforever-project.ts
  src/app/import/models/trackforever/mock/mock-trackforever-project.ts
  src/app/import/models/trackforever/trackforever-issue.ts
  src/app/issue-page/issue-page.component.html
Labels: bug

#138 [Fix] GitHub only import issues
  src/app/import/import-github/import-github.service.ts
  src/app/import/import-github/models/github-comment.ts
  src/app/import/import-github/models/github-issue.ts
  src/app/import/import-github/models/github-label.ts
  src/app/import/import-github/models/github-owner.ts
  src/app/import/import-github/models/github-project.ts
Labels: bug

#139 [Fix] messy layout and margins
  src/app/issue-page/issue-page.component.html
  src/app/my-projects-page/my-projects-page.component.html
  src/app/project-page/project-page.component.html
  src/app/user-page/user-page.component.html
Labels: user interface

#144 Fix sign in to be more persistent again
  .travis.yml
  src/app/authentication/authentication.service.ts
  src/app/shared/guards/auth.guard.spec.ts
  src/app/shared/guards/auth.guard.ts
Labels: bug

#148 [Fix] change the JSON representation of the issue array
  src/app/export/export.service.spec.ts
  src/app/export/export.service.ts
  src/app/import/import-trackforever/import-trackforever.service.spec.ts
  src/app/import/import-trackforever/import-trackforever.service.ts
Labels: enhancement, scalability

#150 Add editable labels and assignees
  src/app/app.module.ts
  src/app/create-issue-page/create-issue-page.component.css
  src/app/create-issue-page/create-issue-page.component.html
  src/app/create-issue-page/create-issue-page.component.spec.ts
  src/app/create-issue-page/create-issue-page.component.ts
  src/app/issue-details/issue-details.component.css
  src/app/issue-details/issue-details.component.html
  src/app/issue-details/issue-details.component.spec.ts
  src/app/issue-details/issue-details.component.ts
  src/app/issue-page/issue-page.component.css
  src/app/issue-page/issue-page.component.html
  src/app/issue-page/issue-page.component.spec.ts
  src/app/issue-page/issue-page.component.ts
  src/app/project-page/project-page.component.html
Labels: user interface

#149 Send & receive json
  src/app/import/import-trackforever/import-trackforever.service.ts
  src/app/issue/online-issue.service.spec.ts
  src/app/issue/online-issue.service.ts
Labels: bug, help wanted

#165 [Fix] align content and stop page jumping
  package-lock.json
  package.json
  src/app/create-issue-page/create-issue-page.component.html
  src/app/import/import-page/import-page.component.html
  src/app/issue-page/issue-page.component.html
  src/app/issue-page/issue-page.component.spec.ts
  src/app/issue-page/issue-page.component.ts
  src/app/issue/default-issue.service.ts
  src/app/my-projects-page/my-projects-page.component.html
  src/app/project-page/project-page.component.html
  src/app/project-page/project-page.component.ts
  src/app/signin-page/signin-page.component.html
  src/app/user-page/user-page.component.html
  src/styles.css
Labels: enhancement, user interface
